
Currently Loaded Modules:
  1) compiler/gnu/14.2   2) devel/python/3.12.3-gnu-14.2   3) devel/cuda/12.8

 

python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
python: can't open file '/pfs/work9/workspace/scratch/ma_fisommer-Dataset/llama-finetune/Data/Py Files/inference_normal.py': [Errno 2] No such file or directory
